server:
  port: 8080

spring:
  application:
    name: P26

  datasource:
    # 팀원 안내사항: 본인의 로컬 MySQL 환경에 맞춰 비밀번호를 수정하고,
    # 이 파일의 이름을 'application.yml'로 변경해서 사용하세요!
    url: jdbc:mysql://localhost:3306/capstone2?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 여기에_본인_DB_비밀번호_입력
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
